### ISSUE TITLE
Add possibility to annotate in an offset.

### ISSUE THREAD

**Issue by brightiup** [jomaway/typst-bytefield#1]
Hello, I really appreciate your work; it has been quite helpful to me. By the way, would it be possible to incorporate something like an `offset` on the left side of the table? This would greatly enhance the representation of data structures when drawing them.

**Comment by jomaway** [comment]
@brightiup thanks, what exactly do you mean by an `offset`.  If i understand correctly you want something like 
```
#import "@preview/bytefield:0.0.1": *
#grid(
  columns: (2cm, 1fr),
  [], ipv4
)
```

Sorry for the late answer i was on vacation.

**Comment by brightiup** [comment]
Thanks for your answer. Is there a way to mark the offset on the left side of this table? This would be useful for describing data structures.

**Comment by jomaway** [comment]
Not at the moment. You need to add annotations in the other side on the grid an need to move them so they fit. But this is not an ideal solution. I would like to integrate something like this but at the moment i don't have enough time. If you would like to contribute feel free.
