### ISSUE TITLE
Roll over indication 

### ISSUE THREAD

**Issue by taylorh140** [jomaway/typst-bytefield#11]
So if a field is too long it is broken across rows. But it doesn’t look very nice. 
![image](https://github.com/jomaway/typst-bytefield/assets/10996543/02e6e1e4-7f69-4e0c-aaa9-7a797cf838d1)
something like this example would be better. Or even a modified right and left edge on the wrap.

im not sure how it would be fixed? But it would be nice.

**Comment by jomaway** [comment]
With version 0.0.4 there is support for nicer looking multirow or row breaks.
