### ISSUE TITLE
Could not fetch from package manager; Archive malformed

### ISSUE THREAD

**Issue by mscofield0** [jomaway/typst-bytefield#2]
The import shown in the README does not work for me: 
`#import "@preview/bytefield:0.0.1": *`
`failed to load package (archive malformed)`

**Comment by jomaway** [comment]
@mscofield0 Should work now, due to vacation it took some time till the package was merged in the package manager. Sorry for the inconvenience.

**Comment by mscofield0** [comment]
No problem, I worked around it by just copying the file locally. Thanks for the fix.
