### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nopeslide** [jomaway/typst-bytefield#20]
Currently only a collection of examples exist.
A more thorough documentation would be needed for the upcoming bump in complexity.

Maybe switch to sth like [mantys](https://github.com/jneug/typst-mantys)?

**Comment by jomaway** [comment]
Sure I am already on that topic, didn't had time to look into mantys yet, but it's on my todo list. What I have done so far is: 

- I updated the `example.typ` yesterday as a first step but it is not complete. 
- Added the new file structure to `CHANGELOG.md`.
