### ISSUE TITLE
Number alignment seems off

### ISSUE THREAD

**Issue by tgross35** [jomaway/typst-bytefield#9]
The number spacing seems a little off to me. For example:

<img width="795" alt="image" src="https://github.com/jomaway/typst-bytefield/assets/13724985/e4f7b0f6-7df0-456c-9344-a7f485366b16">

The `0` and `31` are pretty close to directly over their lines, but the other numbers are pretty clearly to the right of the line.

I think it would be better if each number was centered over that bit's position. I think most numbers are, it just seems like the outside numbers are not

<img width="774" alt="image" src="https://github.com/jomaway/typst-bytefield/assets/13724985/0686c6e6-803f-4c71-b63a-b059cca7a96a">

**Comment by jomaway** [comment]
Hey thanks for the info. 
All bit numbers were centered till the previous release. I would agree that it looks better if showing a field with 32 bit. 
But sometimes, for example with an only 16 bit wide bytefield it starts to look strange too.

![Bildschirmfoto vom 2023-11-30 10-46-32](https://github.com/jomaway/typst-bytefield/assets/22931557/c11a60ee-3ba7-48e8-9a17-60ca45d416d5)  (Here are the 1 and 16 edge aligned already, like you mentioned)

So i started tinkering around how to align the numbers closer to the lines, like shown in the next image.
![Bildschirmfoto vom 2023-11-30 10-46-32](https://github.com/jomaway/typst-bytefield/assets/22931557/2a78b3f9-3f53-4b15-83a3-2f78f1491453)

I didn't had the time to finish this feature yet, as it needs some evaluation if the number should be right or left aligned. 
My plan is also to make a option to set all centered or to evaluate which might look better and use the defaults depending on that. 

If you have any suggestion or opinion on that let me know.

**Comment by jomaway** [comment]
With the refactor all header cells are back to center alignment. So i guess this issue is fixed for now. 
I might add some options for bounding header alignments later.
